/*-----------------------------------------------------------------------*/
/* Copyright (c) Team 501 - The PowerKnights. All Rights Reserved.       */
/* Open Source Software - may be modified and shared by other FRC teams  */
/* under the terms of the Team501 license. The code must be accompanied  */
/* by the Team 501 - The PowerKnights license file in the root directory */
/* of this project.                                                      */
/*-----------------------------------------------------------------------*/

// WARNING: This file is automatically generated in build.gradle

package frc.robot.config;

/**
 * This class provides a versioning string that can be used to determine the
 * build pedigree of a robot as loaded on the roboRIO.
 * <p>
 * Unfortunately, Git doesn't provide a way to automate this the way other CM
 * tools do with keyword expansions.
 **/
class BuildVersionInfo {
    public static final String programmer = "Stu-PID";
    public static final String commitSHA = "9bf37f3";
    public static final String timeStamp = "20240113-145718";
}
